webcams = dict()
webcams['London'] = 'https://www.earthcam.com/world/england/london/abbeyroad/?cam=abbeyroad_uk'
webcams['NYC'] = 'https://www.earthcam.com/usa/newyork/timessquare/?cam=tsrobo1'
webcams['Dublin'] = 'https://www.earthcam.com/world/ireland/dublin/?cam=templebar'
webcams['Prague'] = 'https://www.earthcam.com/world/czechrepublic/prague/?cam=grandhotel_str'
webcams['Elburg'] = 'https://www.youtube.com/watch?v=vPxAgn3EtDQ' 
# webcams['dublinpub'] = 'https://www.earthcam.com/world/ireland/dublin/?cam=dublinpub'
webcams['Bruges'] = 'https://www.skylinewebcams.com/de/webcam/belgique/flandres/bruges/bruges.html'
webcams['Venice'] = 'https://www.youtube.com/watch?v=HpZAez2oYsA'
webcams['Amsterdam'] = 'https://www.youtube.com/watch?v=hBnhSxlL9So'
