webcams = dict()
webcams['london'] = 'https://www.earthcam.com/world/england/london/abbeyroad/?cam=abbeyroad_uk'
webcams['NYC'] = 'https://www.earthcam.com/usa/newyork/timessquare/?cam=tsrobo1'
webcams['dublin'] = 'https://www.earthcam.com/world/ireland/dublin/?cam=templebar'
webcams['prague'] = 'https://www.earthcam.com/world/czechrepublic/prague/?cam=grandhotel_str'
webcams['elburg'] = 'https://www.youtube.com/watch?v=vPxAgn3EtDQ' 
# webcams['dublinpub'] = 'https://www.earthcam.com/world/ireland/dublin/?cam=dublinpub'
webcams['bruges'] = 'https://www.skylinewebcams.com/de/webcam/belgique/flandres/bruges/bruges.html'
webcams['venice'] = 'https://www.youtube.com/watch?v=HpZAez2oYsA'
webcams['amsterdam'] = 'https://www.youtube.com/watch?v=hBnhSxlL9So'
